# Generated by Django 4.1.3 on 2022-12-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0002_remove_account_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
