# Generated by Django 4.1.3 on 2022-12-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0003_account_id_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
