# Generated by Django 4.1.3 on 2022-12-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("its", "0006_task_statement"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="statement",),
    ]
