# Generated by Django 4.1.3 on 2023-01-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0006_task_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
