# Generated by Django 4.1.3 on 2023-01-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0007_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/taskImages/'),
        ),
    ]
