# Generated by Django 4.1.3 on 2023-01-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("its", "0008_alter_task_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="difficulty",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="dimension",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
