# Generated by Django 4.1.3 on 2023-01-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("its", "0010_alter_task_difficulty_alter_task_dimension"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="dimension",),
        migrations.AddField(
            model_name="task",
            name="sizeFactor",
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="difficulty",
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
