# Generated by Django 4.1.3 on 2023-01-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("its", "0011_remove_task_dimension_task_sizefactor_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="date",),
        migrations.AddField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
