# Generated by Django 4.1.3 on 2023-01-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0013_task_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated',
        ),
    ]
