# Generated by Django 4.1.3 on 2023-01-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0015_alter_task_dcl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dcl',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
