# Generated by Django 4.1.3 on 2023-01-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("its", "0016_alter_task_dcl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("task", models.ManyToManyField(related_name="tags", to="its.task")),
            ],
        ),
    ]
