# Generated by Django 4.1.3 on 2023-01-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0016_alter_task_dcl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/taskImages/'),
        ),
    ]
