# Generated by Django 4.1.3 on 2023-01-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0017_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='opened_second_time',
            field=models.BooleanField(default=False),
        ),
    ]
