# Generated by Django 4.1.3 on 2023-01-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("its", "0018_rename_task_tag_tasks"),
        ("its", "0019_remove_task_opened_second_time"),
    ]

    operations = []
