# Generated by Django 4.1.3 on 2023-01-13 20:17

from django.db import migrations, models
import its.models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0020_merge_20230112_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=its.models.upload_image),
        ),
    ]
