# Generated by Django 4.1.3 on 2023-01-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("its", "0021_alter_tag_name_alter_task_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="fxEquation",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="fyEquation",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="mEquation",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
