# Generated by Django 4.1.3 on 2023-01-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("its", "0021_alter_tag_name_alter_task_image"),
        ("its", "0021_alter_task_image"),
    ]

    operations = []
