# Generated by Django 4.1.3 on 2023-01-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("its", "0022_task_fxequation_task_fyequation_task_mequation"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="fxCorrect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="fyCorrect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="mCorrect",
            field=models.BooleanField(default=False),
        ),
    ]
